### PR TITLE
Fix NPE when calling DDLambda

### PR DESCRIPTION
**Pull request by CurtisEppel**
### What does this PR do?

When calling DDLambda(context) the following exception is thrown
```
java.lang.NullPointerException: java.lang.NullPointerExceptionjava.lang.NullPointerException
at io.opentracing.propagation.TextMapExtractAdapter.iterator(TextMapExtractAdapter.java:38)
at datadog.trace.bootstrap.instrumentation.api.ContextVisitors$EntrySetContextVisitor.forEachKey(ContextVisitors.java:55)
at datadog.trace.bootstrap.instrumentation.api.ContextVisitors$EntrySetContextVisitor.forEachKey(ContextVisitors.java:49)
at datadog.trace.agent.core.propagation.TagContextExtractor.extract(TagContextExtractor.java:27)
at datadog.trace.agent.core.propagation.HttpCodec$CompoundExtractor.extract(HttpCodec.java:97)
at datadog.trace.agent.core.CoreTracer.extract(CoreTracer.java:405)
at datadog.trace.instrumentation.opentracing32.OTTracer.extract(OTTracer.java:68)
at io.opentracing.util.GlobalTracer.extract(GlobalTracer.java:204)
at com.datadoghq.datadog_lambda_java.DDLambda.startSpan(DDLambda.java:139)
at com.datadoghq.datadog_lambda_java.DDLambda.<init>(DDLambda.java:53)
```

This was fixed by applying the fix recommended in https://github.com/DataDog/datadog-lambda-java/issues/34.

### Motivation
Deploying a production Kotlin Lambda that I'd like to trace.

### Types of changes

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Misc (docs, refactoring, dependency upgrade, etc.)

### Checklist

- [ ] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [ ] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog

### CODE REVIEW

**Review by agocs — APPROVED** [review]
Hi Curtis, this is a good catch. Thank you for this contribution!

**Comment by agocs** [comment]
I'll push 0.2.2 later this afternoon.

**Comment by agocs** [comment]
Update: Bintray is giving me some problems right now. It _says_ I've published 0.2.2, but I can't verify that. I'll check tomorrow morning and create a new github release if it worked.

**Comment by CurtisEppel** [comment]
Thanks @agocs

**Comment by CurtisEppel** [comment]
I'm able to see `0.2.2` in Bintray - https://bintray.com/beta/#/datadog/datadog-maven/datadog-lambda-java/0.2.2?tab=overview

I'll give it a go today.

**Comment by agocs** [comment]
Awesome! Let me know if you run into anything else!

**Pull request merged**
